kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: anonymous-grafana-proxy-role
rules:
- apiGroups:
  - ""
  resources:
  - "services/proxy"
  resourceNames:
  - "https:monitoring-grafana:"
  verbs:
  - get
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: anonymous-grafana-proxy-binding
  namespace: ""
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: anonymous-grafana-proxy-role
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:anonymous
